### ISSUE TITLE
I got another porblem in debian on desk

### ISSUE THREAD

**Issue by AlanYiNew** [seL4/camkes-manifest#2]
/usr/bin/ld: /home/gyi/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/rts/libCffi.a(closures.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/gyi/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/rts/libCffi.a(ffi64.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Exit code ExitFailure 1 while running ["ghc","-clear-package-db","-global-package-db","-hide-all-packages","-package","base","-package","Cabal-1.22.5.0","/tmp/stack6892/Setup.hs","-o","/home/gyi/.stack/setup-exe-cache/x86_64-linux/tmp-setup-Simple-Cabal-1.22.5.0-ghc-7.10.3","-rtsopts"] in /tmp/stack6892/

I don't know how to compile it into .so or use any other solutions to solve the problem. Besides, I will send you the out put later about the "L letter" on ubuntu building.

**Comment by kent-mcleod** [comment]
This looks like an issue with installing dependencies for the capDL translation tool.  I recall that this occurred due to host distro default compilation settings (https://github.com/haskell/haskell-platform/issues/272).  It's possible to use a pre-built docker image to avoid these dependency clashes: https://docs.sel4.systems/HostDependencies
